MvcNetCoreEF2022/Models/Doctor.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace MvcNetCoreEF2022.Models
{
    [Table("DOCTOR")]
    public class Doctor
    {
        [Key]
        [Column("DOCTOR_NO")]
        public int IdDoctor { get; set; }
        [Column("APELLIDO")]
        public String Apellido { get; set; }
        [Column("ESPECIALIDAD")]
        public String Especialidad { get; set; }
        [Column("SALARIO")]
        public int Salario { get; set; }
        [Column("HOSPITAL_COD")]
        public int IdHospital { get; set; }
    }
}

MvcNetCoreEF2022/Models/ErrorViewModel.cs
using System;

namespace MvcNetCoreEF2022.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcNetCoreEF2022/Models/Hospital.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema; //para el mapeo de las columnas 
using System.Linq;
using System.Threading.Tasks;

namespace MvcNetCoreEF2022.Models
{
    [Table("HOSPITAL")]
    public class Hospital
    {
        [Key]
        [Column("HOSPITAL_COD")]
        public int IdHospital { get; set; }
        [Column("NOMBRE")]
        public String Nombre { get; set; }
        [Column("DIRECCION")]
        public String Direccion { get; set; }
        [Column("TELEFONO")]
        public String Telefono { get; set; }
        [Column("NUM_CAMA")]
        public int Camas { get; set; }
    }
}

MvcNetCoreEF2022/Controllers/DoctoresController.cs
using Microsoft.AspNetCore.Mvc;
using MvcNetCoreEF2022.Models;
using MvcNetCoreEF2022.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcNetCoreEF2022.Controllers
{
    public class DoctoresController : Controller
    {
        private RepositoryDoctores repo;

        // constructor para las dependencias
        public DoctoresController(RepositoryDoctores repo) 
        {
            this.repo = repo;
        }
        public IActionResult DoctoresHospital(int idhospital) 
        {
            List<Doctor> doctores = this.repo.GetDoctoresHospital(idhospital);
            return View(doctores);
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult DoctoresSalario() 
        {
            List<Doctor> doctores = this.repo.GetDoctores();
            return View(doctores);
        }
        [HttpPost]
        public IActionResult DoctoresSalario(int salario) 
        {
            List<Doctor> doctores = this.repo.GetDoctoresSalario(salario);
            if (doctores == null)
            {
                ViewData["mensaje"] = "No hay doctores con ese salario.";
                return View();
            }
            else 
            {
                return View(doctores);
            }
        }
    }
}

MvcNetCoreEF2022/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MvcNetCoreEF2022.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MvcNetCoreEF2022.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcNetCoreEF2022/Controllers/HospitalesController.cs
using Microsoft.AspNetCore.Mvc;
using MvcNetCoreEF2022.Models;
using MvcNetCoreEF2022.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcNetCoreEF2022.Controllers
{
    public class HospitalesController : Controller
    {
        private RepositoryHospitales repo;
        //resolvemos las dependencias 
        public HospitalesController(RepositoryHospitales repo) 
        {
            this.repo = repo;
        }
        public IActionResult Index()
        {
            //recuperamos los hospitales 
            List<Hospital> hospitales = this.repo.GetHospitales();
            //se lo enviamos a la vista
            return View(hospitales);
        }
        public IActionResult Details(int idhospital) 
        {
            Hospital hospital = this.repo.FindHospital(idhospital);
            return View(hospital);
        }
    }
}

MvcNetCoreEF2022/Views/Doctores/DoctoresHospital.cshtml
@model IEnumerable<MvcNetCoreEF2022.Models.Doctor>

@{
    ViewData["Title"] = "DoctoresHospital";
}

<h1>DoctoresHospital</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdDoctor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Apellido)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Especialidad)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Salario)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdHospital)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdDoctor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Apellido)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Especialidad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Salario)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdHospital)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

MvcNetCoreEF2022/Views/Doctores/DoctoresSalario.cshtml
@model List<Doctor>

<form method="post">
    <label>
        Introducir salario:
    </label>
    <input type="text" name="salario" />
    <button type="submit" class="btn btn-info">
        Buscar Doctores
    </button>
</form>

<h1 style="color:red">
    @ViewData["mensaje"]
</h1>
@if (Model != null)
{
    <table class="table table-dark">
        <thead>
            <tr>
                <th>HOSPITAL_COD</th>
                <th>DOCTOR_NO</th>
                <th>APELLIDO</th>
                <th>ESPECIALIDAD</th>
                <th>SALARIO</th>
            </tr>
        </thead>
        <tbody>
            @foreach (Doctor d in Model)
            {
                <tr>
                    <td>@d.IdHospital</td>
                    <td>@d.IdDoctor</td>
                    <td>@d.Apellido</td>
                    <td>@d.Especialidad</td>
                    <td>@d.Salario</td>
                </tr>
            }
        </tbody>
    </table>
}

MvcNetCoreEF2022/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MvcNetCoreEF2022/Views/Hospitales/Details.cshtml
@model MvcNetCoreEF2022.Models.Hospital

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Hospital</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdHospital)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdHospital)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Direccion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Direccion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Telefono)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Telefono)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Camas)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Camas)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

MvcNetCoreEF2022/Views/Hospitales/Index.cshtml
@model  List<Hospital>

<h1>Entity Framework Hospitales</h1>

<table class="table table-active">
    <thead>
        <tr>
            <th>NOMBRE</th>
            <th>DIRECCION</th>
            <th>TELEFONO</th>
            <th>CAMAS</th>
            <td></td>
        </tr>
    </thead>
    <tbody>
         @foreach (Hospital h in Model) 
         {
            <tr>
                <td>@h.Nombre</td>
                <td>@h.Direccion</td>
                <td>@h.Telefono</td>
                <td>@h.Camas</td>
                <td>
                    <a asp-controller="Hospitales"
                       asp-action="Details"
                       asp-route-idhospital="@h.IdHospital"
                       class="btn btn-success">
                        Detalles
                    </a>
                    <a asp-controller="Doctores"
                       asp-action="DoctoresHospital"
                       asp-route-idhospital="@h.IdHospital"
                       class="btn btn-warning">
                        Doctores
                    </a>
                </td>
            </tr>
         }
    </tbody>
</table>

MvcNetCoreEF2022/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcNetCoreEF2022</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcNetCoreEF2022</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark"
                               asp-controller="Hospitales"
                               asp-action="Index">
                                Hospitales EF
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark"
                               asp-controller="Doctores"
                               asp-action="DoctoresSalario">
                                Doctores Salario
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MvcNetCoreEF2022 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>